version: '3.8'
services:
  redis:
    image: 'redis:latest'
    container_name: 'redis_cache'
    ports:
      - '6379:6379'

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telema_app1
    environment:
      - SPRING_PROFILES_ACTIVE=instance1
    ports:
      - '8081:8080'
    depends_on:
      - redis

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telema_app2
    environment:
      - SPRING_PROFILES_ACTIVE=instance2
    ports:
      - '8082:8080'
    depends_on:
      - redis
