services:
  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  app-instance1:
    build: .
    container_name: app-instance1
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: instance1
    depends_on:
      - redis

  app-instance2:
    build: .
    container_name: app-instance2
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: instance2
    depends_on:
      - redis
